export const appTitle = 'Starter'
export const appDescription = 'app description'
export const appNameFA = 'Starter'
export const appNameEn = 'Starter'
export const appDesktopStartMinWidth = '(min-width: 1024px)'
